### ISSUE TITLE
GitLab: Exempt special top-level keywords from job label scopes

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/YamlPipelines#10]
Some keys on the top level are reserved and are in fact not job labels/names, thus should not be scoped as such.

This should be the complete list of supported global keywords:

- `variables`
- `default`
- `workflow`
- `include`
- `stages`

[Documentation](https://docs.gitlab.com/ee/ci/yaml/#global-keywords)

**Comment by keith-hall** [comment]
fixed in https://github.com/SublimeText/YamlPipelines/commit/8489e728ffba9b5fe89a190f774ddb067bc2157b
