### ISSUE TITLE
Wrong filename for Azure Pipelines

### ISSUE THREAD

**Issue by jwortmann** [SublimeText/YamlPipelines#17]
https://github.com/SublimeText/YamlPipelines/blob/55667795d2d40cfa061d28462fd01f4616fc074e/AzureDevops.sublime-syntax#L10

The file name should be `azure-pipelines.yml`

See https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started/pipelines-get-started?view=azure-devops#define-pipelines-using-yaml-syntax

**Comment by keith-hall** [comment]
Thanks for reporting. Fixed in c9a854f28d9a12585eb84d07367c3cde2b7492c4
