### ISSUE TITLE
Handle folded block scalars in script blocks

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/YamlPipelines#19]
Literal Style block scalars (`|`) are generally handled properly, but folded block scalars (`>`) confuse the syntax because each newline is treated as a newline in shell when it is actually an implicit line continuation.

This syntax is sometimes advantageous when using many arguments in a call and definitely preferrable from a syntax perspective over an implicit unqouted multi-line scalar or even a quoted multi-line scalar.

Syntax documentation: https://yaml.org/spec/1.2.2/#813-folded-style

Example (using GitLab syntax):

```yaml
release-finish:
  extends: release
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release\//
      when: manual
  script:
    - NEW_VERSION="${NEW_VERSION:-${CI_COMMIT_BRANCH#release/}}"
    - >-
      mvn
      --batch-mode
      $MAVEN_CLI_OPTS_DEFAULT
      $MAVEN_CLI_OPTS
      $MAVEN_GITFLOW_CLI_OPTS
      gitflow:release-finish
      -DpushRemote=true
      -DreleaseVersion="${NEW_VERSION}"
      -DskipTestProject=true
```

**Comment by michaelblyons** [comment]
Would you expect to make a new Bash embed file that puts a `- match '\n'` in the prototype? Or prepend it judiciously? Or override to strip all the newline pops in every context that has them?

**Comment by FichteFoll** [comment]
I think I'd try going with an `embed` that back-references the number of spaces used on the first block scalar line and then use a prototype that just swallows *all* new-lines, ideally as a re-usable extended syntax.
