### ISSUE TITLE
Inject variables into Bash

### ISSUE THREAD

**Issue by michaelblyons** [SublimeText/YamlPipelines#3]
Make an `extends: /Packages/ShellScript/Bash.sublime-syntax` language that adds `${{`&hellip;`}}` etc. in the appropriate places.

**Comment by keith-hall** [comment]
initial work completed in https://github.com/SublimeText/YamlPipelines/commit/5ca54c38b1649e27624f32ba1ac976777c0b8c6a, but I suspect there will be more places that need it, I just don't have examples/syntax tests for them yet. Contributions welcome!

**Comment by deathaxe** [comment]
Rather sounds like a job for `embed: Bash.sublime-syntax`
